### PR TITLE
Do not Initialize Flare Client with Wrong Evaluation Strategy

### LINKED ISSUE #93: Exception when starting plugin having CQL configured
Flare client gets initialized when basic auth credentials are configured even if evaluation strategy is 'cql'.

see [FlareWebserviceClientSpringConfig.java#L118](https://github.com/medizininformatik-initiative/feasibility-dsf-process/blob/develop/feasibility-dsf-process/src/main/java/de/medizininformatik_initiative/feasibility_dsf_process/client/flare/FlareWebserviceClientSpringConfig.java#L118)

### PR DESCRIPTION
**Pull request by EmteZogaf**
Create flare client which throws error message only on actual usage.

closes #93

### CODE REVIEW

File: feasibility-dsf-process/src/main/java/de/medizininformatik_initiative/feasibility_dsf_process/client/flare/FlareWebserviceClientSpringConfig.java [hunk 1]
```diff
@@ -69,60 +71,79 @@ public class FlareWebserviceClientSpringConfig {
...
 
     @Bean
-    public FlareWebserviceClient flareWebserviceClient(HttpClient httpClient) {
-        return new FlareWebserviceClient() {
-
-            FlareWebserviceClient client;
+    public FlareWebserviceClient flareWebserviceClient(HttpClient httpClient,
+                                                       EvaluationSettingsProvider evaluationSettingsProvider) {
+        if (EvaluationStrategy.STRUCTURED_QUERY.getStrategyRepresentation()
+                .equals(evaluationSettingsProvider.evaluationStrategyRepresentation())) {
```
Comment (alexanderkiel) [inline feasibility-dsf-process/src/main/java/de/medizininformatik_initiative/feasibility_dsf_process/client/flare/FlareWebserviceClientSpringConfig.java:77]: Please evaluate wether the enum can be compared here directly.

**Review by alexanderkiel — CHANGES_REQUESTED** [review]

File: feasibility-dsf-process/src/main/java/de/medizininformatik_initiative/feasibility_dsf_process/client/flare/FlareWebserviceClientSpringConfig.java [hunk 2]
```diff
@@ -69,60 +71,77 @@ public class FlareWebserviceClientSpringConfig {
     private String bearerAuthToken;
 
     @Bean
-    public FlareWebserviceClient flareWebserviceClient(HttpClient httpClient) {
-        return new FlareWebserviceClient() {
-
-            FlareWebserviceClient client;
+    public FlareWebserviceClient flareWebserviceClient(HttpClient httpClient,
+                                                       EvaluationSettingsProvider evaluationSettingsProvider) {
+        if (EvaluationStrategy.STRUCTURED_QUERY.equals(evaluationSettingsProvider.evaluationStrategy())) {
```
Comment (alexanderkiel) [inline feasibility-dsf-process/src/main/java/de/medizininformatik_initiative/feasibility_dsf_process/client/flare/FlareWebserviceClientSpringConfig.java:76]: You can use `==` here.

File: feasibility-dsf-process/src/main/java/de/medizininformatik_initiative/feasibility_dsf_process/client/flare/FlareWebserviceClientSpringConfig.java [hunk 3]
```diff
@@ -69,60 +71,77 @@ public class FlareWebserviceClientSpringConfig {
...
+            return createFlareClient(httpClient);
+        } else {
+            return new ErrorFlareWebserviceClient(new IllegalStateException(
+                    format("EVALUATION_STRATEGY is not set to '%s'.",
+                            EvaluationStrategy.STRUCTURED_QUERY.getStrategyRepresentation())));
```
Comment (alexanderkiel) [inline feasibility-dsf-process/src/main/java/de/medizininformatik_initiative/feasibility_dsf_process/client/flare/FlareWebserviceClientSpringConfig.java:81]: I would override `toString()` here and the the enum as is with `%s`.

File: feasibility-dsf-process/src/test/java/de/medizininformatik_initiative/feasibility_dsf_process/EvaluationSettingsProviderImplTest.java [hunk 4]
```diff
@@ -19,7 +19,7 @@ public void testEvaluationStrategyRepresentation() {
         EvaluationSettingsProvider provider;
         for (EvaluationStrategy strategy : EvaluationStrategy.values()) {
             provider = new EvaluationSettingsProviderImpl(strategy, false, 0d, 0d, 0, Duration.ofSeconds(1));
-            assertEquals(strategy.getStrategyRepresentation(), provider.evaluationStrategyRepresentation());
+            assertEquals(strategy, provider.evaluationStrategy());
```
Comment (alexanderkiel) [inline feasibility-dsf-process/src/test/java/de/medizininformatik_initiative/feasibility_dsf_process/EvaluationSettingsProviderImplTest.java:22]: assertSame
